name = "photolive"

[site]
bucket = ".next"

[build]
command = "npm run build"

[build.upload]
format = "directory"

[site.production]
pages_build_output_dir = ".next"

[env.production]
compatibility_date = "2025-04-24" 