<<<<<<< HEAD
name = "photolive"

[site]
bucket = ".next"

[build]
command = "npm run build"

[build.upload]
format = "directory"

[site.production]
pages_build_output_dir = ".next"

[env.production]
=======
name = "photolive"

[site]
bucket = ".next"

[build]
command = "npm run build"

[build.upload]
format = "directory"

[site.production]
pages_build_output_dir = ".next"

[env.production]
>>>>>>> e5fbdc63614b3061b16a5b3cc64c6080b9f29419
compatibility_date = "2025-04-24" 